name: My APK Build

on:
  push:
    branches:
      - kushagra

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - uses: subosito/flutter-action@v2

      - run: flutter pub get
        working-directory: mobile/ble_attendance_mobile

      - run: flutter build apk --release
        working-directory: mobile/ble_attendance_mobile
